<?php
/**
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 *
 * @license GPL 2.0
 * @package Comwrap/Pdf/Templates
 * @author Thomas Spigel <tspigel@comwrap.com>
 * @version 1.0
 *
 * @var $this Comwrap_Pdf_Block_Creditmemo
 */
$logoUrl = $this->getSkinUrl(Mage::getStoreConfig('design/header/logo_src'));
$svgLogo = <<<EOSVG
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 width="2.84cm" height="2.32cm" viewBox="0 0 142 116" enable-background="new 0 0 142 116" xml:space="preserve">
<g>
	<path d="M91.438,21.14L80.855,10.559c-0.714-0.852-2.554-2.2-5.259-2.2H55.875c-3.686,0-6.684,2.998-6.684,6.684v51.792
		c0,3.687,2.999,6.686,6.684,6.686h31.207c3.685,0,6.685-2.999,6.685-6.686V26.899C93.767,23.308,91.949,21.56,91.438,21.14z
		 M55.875,11.277h19.721c2.027,0,3.003,1.132,3.029,1.164l0.054,0.068l10.752,10.754l0.146,0.126c0.051,0.04,1.27,1.046,1.27,3.51
		v11.444c-1.19,0.242-2.463,0.386-3.815,0.386c-4.894,0-9.928-1.842-14.968-5.47c-5.389-3.882-10.82-5.85-16.14-5.85
		c-1.346,0-2.62,0.13-3.815,0.346V15.043C52.109,12.967,53.798,11.277,55.875,11.277z M87.082,70.599H55.875
		c-2.076,0-3.765-1.687-3.765-3.764V48.031c1.189-0.242,2.461-0.386,3.815-0.386c4.888,0,9.928,1.838,14.967,5.468
		c5.388,3.881,10.821,5.851,16.142,5.851c1.348,0,2.618-0.131,3.815-0.347v8.218C90.848,68.912,89.161,70.599,87.082,70.599z"/>
	<g>
		<g>
			<path d="M17.174,85.573c0,2.625-3.98,2.625-3.98,0C13.194,82.945,17.174,82.945,17.174,85.573z M13.286,89.829v15.385h3.793
				V89.829H13.286z"/>
			<path d="M31.468,105.214v-8.017c0-2.332-1.272-4.102-3.7-4.102c-2.33,0-3.912,1.957-3.912,4.288v7.832h-3.764V89.862h3.627
				l0.008,2.082c1.555-1.524,3.111-2.3,5.038-2.3c3.606,0,6.497,2.703,6.497,7.521v8.049H31.468z"/>
			<path d="M48.218,93.963c-1.084-1.025-2.329-1.369-3.788-1.369c-1.807,0-2.799,0.561-2.799,1.526c0,0.994,0.899,1.552,2.859,1.675
				c2.889,0.186,6.558,0.841,6.558,4.912c0,2.706-2.208,5.035-6.588,5.035c-2.424,0-4.852-0.404-7.087-2.734l1.864-2.706
				c1.09,1.214,3.576,2.113,5.283,2.146c1.433,0.03,2.771-0.716,2.771-1.833c0-1.056-0.872-1.493-3.045-1.616
				c-2.895-0.217-6.342-1.273-6.342-4.754c0-3.544,3.665-4.789,6.464-4.789c2.392,0,4.194,0.47,5.965,2.025L48.218,93.963z"/>
			<path d="M58.505,85.573v4.352h4.227v3.261h-4.256v6.62c0,1.462,0.807,2.177,1.987,2.177c0.591,0,1.274-0.187,1.834-0.465
				l1.057,3.232c-1.087,0.435-1.989,0.621-3.14,0.651c-3.326,0.126-5.499-1.769-5.499-5.595v-6.62h-2.861v-3.261h2.861v-3.948
				L58.505,85.573z"/>
			<path d="M77.271,89.893h3.764v15.321h-3.764l0.004-2.238c-0.867,1.802-3.264,2.673-4.972,2.704
				c-4.538,0.032-7.894-2.765-7.894-8.14c0-5.286,3.513-8.05,7.991-8.021c2.048,0,4.009,0.966,4.875,2.489L77.271,89.893z
				 M68.199,97.54c0,2.921,2.024,4.661,4.541,4.661c5.967,0,5.967-9.294,0-9.294C70.224,92.906,68.199,94.615,68.199,97.54z"/>
			<path d="M93.935,93.963c-1.09-1.025-2.333-1.369-3.792-1.369c-1.803,0-2.799,0.561-2.799,1.526c0,0.994,0.902,1.552,2.859,1.675
				c2.892,0.186,6.558,0.841,6.558,4.912c0,2.706-2.207,5.035-6.588,5.035c-2.424,0-4.848-0.404-7.087-2.734l1.867-2.706
				c1.085,1.214,3.572,2.113,5.283,2.146c1.429,0.03,2.764-0.716,2.764-1.833c0-1.056-0.869-1.493-3.042-1.616
				c-2.891-0.217-6.345-1.273-6.345-4.754c0-3.544,3.671-4.789,6.467-4.789c2.393,0,4.194,0.47,5.967,2.025L93.935,93.963z"/>
			<path d="M102.681,85.536c0,2.521-3.825,2.521-3.825,0C98.856,83.013,102.681,83.013,102.681,85.536z M98.873,89.829v15.385h3.792
				V89.829H98.873z"/>
			<path d="M115.965,105.214v-8.206c0-2.022-1.057-3.853-3.138-3.853c-2.052,0-3.266,1.831-3.266,3.853v8.206h-3.788V89.862h3.777
				l0.01,1.864c0.809-1.554,2.58-2.114,4.042-2.114c1.833,0,3.666,0.746,4.538,2.859c1.366-2.175,3.138-2.794,5.128-2.794
				c4.35,0,6.493,2.67,6.493,7.27v8.268h-3.792v-8.268c0-2.021-0.838-3.729-2.887-3.729c-2.051,0-3.327,1.77-3.327,3.792v8.206
				H115.965z"/>
		</g>
	</g>
</g>
</svg>
EOSVG;
$_helper = Mage::helper('comwrap_pdf');

$i = 0;
?>

<head>
    <style type="text/css">
        body {
            font-size: 9pt;
            font-family: "helvetica";
        }
        h1 {
            text-align: center;
            padding: 0;
            margin: 0 auto;
        }
        table
        {
            border-collapse: collapse;
            width: 100%;
            border: 0.5pt solid #737373;
            padding: 0;
        }
        table tr:first-child td:first-child { border-left: 0; border-top: 0; padding:2.5pt 5pt;}
        table td
        {
            padding: 5pt;
        }
        .border-right
        {
            border-right: 0.5pt solid #737373;
        }
        .border-bottom
        {
            border-bottom: 0.5pt solid #737373;
        }
        .no-border
        {
            border: 0;
        }
        thead tr th
        {
            font-weight: bold;
            padding: 5pt;
        }

        .addresses td {
            vertical-align: top;
        }

        .products td {
            padding: 3pt;
            height: 5pt;
            vertical-align: top;
            border: solid #737373;
            border-width: 0 0.5pt 0 0.5pt;
        }

        .products tr.gray td {
            background-color: #f0f0f0;
        }

        .products thead tr {
            padding: 3pt !important;
            height: 5pt;
            background-color: #ebebeb;
        }

        .products thead tr th {
            border: 0.5pt solid #737373;
            font-weight: normal !important;
            padding: 3pt !important;
            height: 5pt;
        }

        .totals td {
            font-weight: bold;
            padding: 3pt;
            padding-right: 0pt;
        }

        .product-options {
            font-size: 8pt;
        }

        .collector-box {
            display: inline-block;
            border-top: 1px solid black;
            text-align: center;
        }

        tr.parent-product td {
            font-weight: bold;
        }
    </style>
</head>
<body>

<?php /* @var $_memo Mage_Sales_Model_Order_Creditmemo */ ?>
<?php foreach($this->getCreditmemo() as $_memo):?>
    <?php $this->startEmulateEnvironment($_memo->getStoreId());?>
    <?php if($i > 0) : ?>
        <pagebreak />
    <?php endif;?>
    <?php

    $this->setOrder($_memo->getOrder());

    /* 
     * ASSUMPTION 1:
     *   The price are either exclusively in the parent or children rows only.
     */

    /*
     * The invoice item collection looks like
     *   Parent Item 1
     *   Child Item 1.1
     *   Child Item 1.2
     *   Parent Item 2
     *   Child Item 2.1
     *   Child Item 2.2
     *    .
     *    .
     *    .
     * .
     * From the above we make something like 
     *   array(
     *     parent_item_1 => array(child_item_1.1, ...)
     *     parent_item_2 => array(child_item_2.1, ...)
     *     ...
     */
    $invoiceItems = array();
    $lastParentItem = null;
    $lastParentItemDeposit = 0;
    $lastParentItemFxCostTotal = 0;
    $lastParentItemTotal = 0;
    $lastParentItemDiscountTotal = 0;
    $lastChildrenList = array();

    $depositItems = array();
    $topupItems = array();
    $depositGrandTotal = 0;
    $fxCostGrandTotal = 0;

    foreach($_memo->getItemsCollection() as $_item) {
        if (
            (strpos($_item->getSku(), 'deposit') !== false)
            and ($_item->getOrderItem()->getParentItem())
        ) {
            // See assumption 1 above
            if ($lastParentItem->getRowTotal()) {
                $p = Mage::getModel('catalog/product')->load($_item->getProductId());
                $_item->setRowTotal($p->getPrice() * $_item->getQty());
            } else {
                $lastParentItemTotal += $_item->getRowTotal();
                $lastParentItemDiscountTotal += $_item->getDiscountAmount();
            }
            $lastParentItemDeposit += $_item->getRowTotal() - $_item->getDiscountAmount();
            $depositGrandTotal += $_item->getRowTotal() - $_item->getDiscountAmount();
            $depositItems[] = $_item;            
            continue;
        }

        if ($_item->getOrderItem()->getParentItem()) {
            $lastChildrenList[] = $_item;
        } else {
            if ($lastParentItem) {
                $lastParentItem->setChildrenItems($lastChildrenList);
                // the parent price is either null/0 or the whole price
                $lastParentItem->setRowTotal(max(
                    0,
                    $lastParentItem->getRowTotal() - $lastParentItemDeposit
                ));
                $lastParentItem->setFxCostTotal($lastParentItemFxCostTotal);
                $fxCostGrandTotal += $lastParentItemFxCostTotal;
                $lastParentItem->setItemTotal($lastParentItemTotal - $lastParentItemDeposit);
                $lastParentItem->setItemDiscountTotal($lastParentItemDiscountTotal);
                $invoiceItems[] = $lastParentItem;
            }
            $lastParentItem = $_item;
            $lastParentItemDeposit = 0;
            $lastParentItemFxCostTotal = 0;
            $lastParentItemTotal = 0;
            $lastParentItemDiscountTotal = 0;
            $lastChildrenList = array();
        }

        if ($_item->getOrderItem()->getTopupUseFxReserve()) {
            $_quoteItem = Mage::getModel('sales/quote_item')->load($_item->getOrderItem()->getQuoteItemId());
            if ($_quoteItem->getId()) {
                $fxd = Mage::getModel('instasim_topupproduct/deposit')->load($_quoteItem->getTopupFxDeposit());
            } else {
                // TOTO: Eventually we should only use this case of the if block
                $fxd = Mage::getModel('instasim_topupproduct/deposit')->load($_item->getOrderItem()->getTopupFxDeposit());
            }

            $fxr = Mage::getModel('instasim_topupproduct/fxreserve')->load($_item->getOrderItem()->getTopupFxReserve());
            $topupFxCost = $_item->getOrderItem()->getTopupFxCost();

            $_item->setUseFxr(1);
            $_item->setFxr($fxr);
            $_item->setFxd($fxd);
            $_item->setTopupFxCost($topupFxCost);
            $_item->setFxCost(round($_item->getQty() * $_item->getTopupFxCost() * $fxd->getExchangeRate(), 2));

            if ($_item->getFxCost()) {
                $topupItems[] = $_item;
                $lastParentItemFxCostTotal += $_item->getFxCost();
            }
        }

        $lastParentItemTotal += $_item->getRowTotal();
        // See assumption 1
        $lastParentItemDiscountTotal += $_item->getDiscountAmount();
    }
    if ($lastParentItem) {
        $lastParentItem->setChildrenItems($lastChildrenList);
        // the parent price is either null/0 or the whole price
        $lastParentItem->setRowTotal(max(
            0,
            $lastParentItem->getRowTotal() - $lastParentItemDeposit
        ));
        $lastParentItem->setFxCostTotal($lastParentItemFxCostTotal);
        $fxCostGrandTotal += $lastParentItemFxCostTotal;
        $lastParentItem->setItemTotal($lastParentItemTotal - $lastParentItemDeposit);
        $lastParentItem->setItemDiscountTotal($lastParentItemDiscountTotal);
        $invoiceItems[] = $lastParentItem;
    }
    $taxableGrandTotalExclTax = round((0.07/1.07) * ($_memo->getGrandTotal() - $depositGrandTotal - $fxCostGrandTotal), 2);
    $taxGrandTotal = $_memo->getGrandTotal() - $depositGrandTotal - $fxCostGrandTotal - $taxableGrandTotalExclTax;
    ?>

    <table class="no-border" style="margin-bottom: 1cm;">
        <tr>
            <td style="width: 18%; padding-left: 0.5cm; height: 3cm; overflow: hidden;">
                <?php echo $svgLogo; ?>
            </td>
            <td style="width: 52%; height: 3cm; overflow: hidden;">
                <?php
                    echo $this->getLayout()->createBlock('cms/block')->setBlockId('store_billing_contact')->toHtml(); 
                ?>
            </td>
            <td style="width: 30%; height: 3cm; overflow: hidden; text-align: right; vertical-align: top;">
                <h1><?php echo $_helper->__('Credit Memo')?></h1><br />
                <?php echo $_helper->__('Credit Memo Number: ') . $_memo->getIncrementId(); ?>
                <br />
                <?php echo $_helper->__('Date: '); ?>
                <?php echo Mage::helper('core')->formatDate($_memo->getCreatedAt(), 'medium', false); ?>
            </td>
        </tr>
    </table>

    <table class="no-border addresses">
        <tr>
            <td style="text-align: right; width: 13%; height: 3cm; overflow: hidden;">
                <div style="position: absolute; rotate: -90; left: 10%; text-align: center; font-size: 70%;">
                    <?php echo $_helper->__('Order # ')?>
                    <br />
                    <barcode code="<?php echo $_memo->getOrder()->getIncrementId()?>" type="C128A" size="0.5" />
                    <br />
                    <?php echo $_memo->getOrder()->getIncrementId()?>
                </div>
            </td>
            <?php if (! empty($_memo->getShippingAddress())): ?>
                <td style="text-align: center; width: 5%; height: 3cm; overflow: hidden;">
                    S<br />
                    H<br />
                    I<br />
                    P<br />
                     <br />
                    T<br />
                    O<br />
                </td>
                <td style="padding: 5pt; text-align: left; width: 52%; height: 3cm; overflow: hidden;">
                    <p class="address-info"><?php echo $_memo->getShippingAddress()->format('html');?></p>
                </td>
                <?php $extra_billing_width = 0; ?>
            <?php else: ?>
                <?php $extra_billing_width = 57; ?>
            <?php endif; ?>
            <td style="text-align: center; width: 5%; height: 3cm; overflow: hidden;">
                S<br />
                O<br />
                L<br />
                D<br />
                 <br />
                T<br />
                O<br />
            </td>
            <td style="padding: 5pt; text-align: left; width: <?php echo (25 + $extra_billing_width) ?>%; height: 3cm; overflow: hidden;">
                <?php if (! empty($_memo->getBillingAddress())): ?>
                    <p class="address-info"><?php echo $_memo->getBillingAddress()->format('html');?></p>
                <?php endif; ?>
            </td>
        </tr>
    </table>
    <table class="products" cellpadding="0" cellspacing="0" style="margin-top: 1.5cm;">
        <thead>
        <tr>
            <th><?php echo $_helper->__('Products'); ?></th>
            <th><?php echo $_helper->__('Qty'); ?></th>
            <th><?php echo $_helper->__('Unit Price'); ?></th>
            <th><?php echo $_helper->__('Price'); ?></th>
        </tr>
        </thead>
        <tbody>
        <?php $grayRow = true; ?>
        <?php /* @var $_item Mage_Sales_Model_Order_Creditmemo_Item */?>
        <?php foreach($invoiceItems as $_item): ?>
            <?php $grayRow = ! $grayRow; ?>
            <tr class="<?php echo $grayRow ? 'gray' : ""; ?> parent-product">
                <?php
                $productOptions = $_item->getOrderItem()->getProductOptions();
                ?>
                <?php if(!empty($productOptions['attributes_info'])): ?>
                    <td>
                        <?php echo $_item->getName();?>
                        <?php foreach($productOptions['attributes_info'] as $productOption):?>
                            <br />
                            <span class="product-options">
                                <i><?php echo $productOption['label']?></i><br />
                                &nbsp;&nbsp;&nbsp;&nbsp;<?php echo $productOption['value'];?>
                            </span>
                        <?php endforeach;?>
                    </td>
                <?php else: ?>
                    <td><?php echo $_item->getName() ?></td>
                <?php endif;?>

                <td style="text-align: right;"><?php echo (int)$_item->getQty() ?></td>
                <td style="text-align: right;"><?php echo Mage::helper('core')->currency(($_item->getItemTotal() - $_item->getFxCostTotal() - $_item->getItemDiscountTotal()) / $_item->getQty()); ?></td>
                <td style="text-align: right;"><?php echo Mage::helper('core')->currency($_item->getItemTotal() - $_item->getFxCostTotal() - $_item->getItemDiscountTotal()); ?></td>
            </tr>
            <?php foreach($_item->getChildrenItems() as $_childItem): ?>
                <tr class="<?php echo $grayRow ? 'gray' : ""; ?>">
                <td style="padding-left: 1cm"><?php echo $_helper->getQtyString($_childItem->getQty()/$_item->getQty()). $_childItem->getName() ?></td>
                    <td style="text-align: right;"></td>
                    <td style="text-align: right;"></td>
                    <td style="text-align: right;"></td>
                </tr>
            <?php endforeach; ?>
        <?php endforeach; ?>
        </tbody>
    </table>
    <br />
    <br /><br />
    <table class="no-border totals" style="" cellpadding="0" cellspacing="0">
        <tbody>
        <tr>
            <td style="width: 20%">&nbsp;</td>
            <td style="text-align: right; width: 65%;"><?php echo $_helper->__('Subtotal');?>:</td>
            <td style="text-align: right; width: 15%;"><?php echo Mage::helper('core')->currency($_memo->getGrandTotal() - $_memo->getShippingInclTax() - $depositGrandTotal - $fxCostGrandTotal)?></td>
        </tr>
        <tr>
            <td style="width: 20%">&nbsp;</td>
            <td style="text-align: right; width: 65%;"><?php echo $_helper->__('Shipping & Handling')?>:</td>
            <td style="text-align: right; width: 15%;"><?php echo Mage::helper('core')->currency($_memo->getShippingInclTax())?></td>
        </tr>
        <tr>
            <td style="width: 20%">&nbsp;</td>
            <td style="text-align: right; width: 65%;"><?php echo $_helper->__('Grand Total')?>:</td>
            <td style="text-align: right; width: 15%;"><?php echo Mage::helper('core')->currency($_memo->getGrandTotal() - $depositGrandTotal - $fxCostGrandTotal)?></td>
        </tr>
        <tr>
            <td style="width: 20%">&nbsp;</td>
            <td style="text-align: right; width: 65%;"><?php echo $_helper->__('Grand Total Excl. VAT')?>:</td>
            <td style="text-align: right; width: 15%;"><?php echo Mage::helper('core')->currency($taxGrandTotal)?></td>
        </tr>
        <tr>
            <td style="width: 20%">&nbsp;</td>
            <td style="text-align: right; width: 65%;"><?php echo $_helper->__('VAT')?>:</td>
        <td style="text-align: right; width: 15%;"><?php echo Mage::helper('core')->currency($taxableGrandTotalExclTax)?></td>
        </tr>
        </tbody>
    </table>
    <?php if ($topupItems): ?>
    <?php /* BEGIN TOPUP RECEIPT {{{ */ ?>
    <pagebreak />
    <table class="no-border" style="margin-bottom: 1cm;">
        <tr>
            <td style="width: 18%; padding-left: 0.5cm; height: 3cm; overflow: hidden;">
                <?php echo $svgLogo; ?>
            </td>
            <td style="width: 52%; height: 3cm; overflow: hidden;">
                <?php 
                    echo $this->getLayout()->createBlock('cms/block')->setBlockId('store_billing_contact')->toHtml(); 
                ?>
            </td>
            <td style="width: 30%; height: 3cm; overflow: hidden; text-align: right; vertical-align: top;">
                <h1><?php echo $_helper->__('Money Receipt')?></h1><br />
                <?php echo $_helper->__('Date: '); ?>
                <?php echo Mage::helper('core')->formatDate($_memo->getCreatedAt(), 'medium', false); ?>
            </td>
        </tr>
    </table>

    <table class="no-border addresses">
        <tr>
            <td style="text-align: right; width: 13%; height: 3cm; overflow: hidden;">
                <div style="position: absolute; rotate: -90; left: 10%; text-align: center; font-size: 70%;">
                    <?php echo $_helper->__('Order # ')?>
                    <br />
                    <barcode code="<?php echo $_memo->getOrder()->getIncrementId()?>" type="C128A" size="0.5" />
                    <br />
                    <?php echo $_memo->getOrder()->getIncrementId()?>
                </div>
            </td>
            <?php if (! empty($_memo->getShippingAddress())): ?>
                <td style="text-align: center; width: 5%; height: 3cm; overflow: hidden;">
                    S<br />
                    H<br />
                    I<br />
                    P<br />
                     <br />
                    T<br />
                    O<br />
                </td>
                <td style="padding: 5pt; text-align: left; width: 52%; height: 3cm; overflow: hidden;">
                    <p class="address-info"><?php echo $_memo->getShippingAddress()->format('html');?></p>
                </td>
                <?php $extra_billing_width = 0; ?>
            <?php else: ?>
                <?php $extra_billing_width = 57; ?>
            <?php endif; ?>
            <td style="text-align: center; width: 5%; height: 3cm; overflow: hidden;">
                S<br />
                O<br />
                L<br />
                D<br />
                 <br />
                T<br />
                O<br />
            </td>
            <td style="padding: 5pt; text-align: left; width: <?php echo (25 + $extra_billing_width) ?>%; height: 3cm; overflow: hidden;">
                <?php if (! empty($_memo->getBillingAddress())): ?>
                    <p class="address-info"><?php echo $_memo->getBillingAddress()->format('html');?></p>
                <?php endif; ?>
            </td>
        </tr>
    </table>
    <table class="products" cellpadding="0" cellspacing="0" style="margin-top: 1.5cm;">
        <thead>
        <tr>
            <th><?php echo $_helper->__('Item'); ?></th>
            <th><?php echo $_helper->__('Qty'); ?></th>
            <th><?php echo $_helper->__('Amount per Unit'); ?></th>
            <th><?php echo $_helper->__('Amount'); ?></th>
        </tr>
        </thead>
        <tbody>
        <?php $grayRow = true; ?>
        <?php /* @var $_item Mage_Sales_Model_Order_Creditmemo_Item */?>
        <?php foreach($invoiceItems as $_item): ?>
            <?php $grayRow = ! $grayRow; ?>
            <?php if ($_item->getFxCost()): ?>
                <tr class="<?php echo $grayRow ? 'gray' : ""; ?>"><!-- The FX Cost -->
                    <td>
                        <b><?php echo $_helper->__('Credit value of %1$.2f %2$s at the exchange rate %3$.4f %4$s/%5$s', $_item->getTopupFxCost(), $_item->getFxr()->getCurrencySymbol(), $_item->getFxd()->getExchangeRate(), Mage::app()->getStore()->getBaseCurrencyCode(), $_item->getFxr()->getCurrencySymbol()); ?></b>(*)
                        <br />
                        <small style="padding-left: 1cm;">&nbsp;&nbsp;**<?php echo $_helper->__(' for ') . $_item->getName() ?></small>
                    </td>
                    <td style="text-align: right;"><?php echo (int)$_item->getQty() ?></td>
                    <td style="text-align: right;"><?php echo Mage::helper('core')->currency($_item->getFxCostTotal() / $_item->getQty()); ?></td>
                    <td style="text-align: right;"><?php echo Mage::helper('core')->currency($_item->getFxCostTotal()); ?></td>
                </tr>
            <?php endif; ?>
            <?php foreach($_item->getChildrenItems() as $_childItem): ?>
                <?php if ($_childItem->getFxCost()): ?>
                    <tr class="<?php echo $grayRow ? 'gray' : ""; ?>"><!-- The FX Cost -->
                        <td>
                            <?php echo $_helper->getQtyString($_childItem->getQty()/$_item->getQty()) . $_helper->__('Credit value of %1$.2f %2$s at the exchange rate %3$.4f %4$s/%5$s', $_childItem->getTopupFxCost(), $_childItem->getFxr()->getCurrencySymbol(), $_childItem->getFxd()->getExchangeRate(), Mage::app()->getStore()->getBaseCurrencyCode(), $_childItem->getFxr()->getCurrencySymbol()); ?>(*)
                            <br />
                            <small style="padding-left: 1cm;">&nbsp;&nbsp;**<?php echo $_helper->__(' for ') . $_item->getName() ?></small>
                        </td>
                        <td style="text-align: right;"><?php echo (int)$_childItem->getQty() ?></td>
                        <td style="text-align: right;"><?php echo Mage::helper('core')->currency($_childItem->getFxCost() / $_item->getQty()); ?></td>
                        <td style="text-align: right;"><?php echo Mage::helper('core')->currency($_childItem->getFxCost()); ?></td>
                    </tr>
                <?php endif; ?>
            <?php endforeach; ?>
        <?php endforeach; ?>
        </tbody>
    </table>
    <br />
    <br /><br />
    <table class="no-border totals" style="" cellpadding="0" cellspacing="0">
        <tbody>
        <tr>
            <td style="width: 60%">&nbsp;</td>
            <td style="text-align: right; width: 25%;"><?php echo $_helper->__('Grand Total')?>:</td>
            <td style="text-align: right; width: 15%;"><?php echo Mage::helper('core')->currency($fxCostGrandTotal)?></td>
        </tr>
        </tbody>
    </table>
    * <?php echo $_helper->__("The exchange rate is based on the bank's rate on the date the company transacted the exchange and not necessarily the rate on the order date.") ?>
    <?php /* }}} END TOPUP RECEIPT */ ?>
    <?php endif; ?>
    <?php ++$i;?>
    <?php $this->stopEmulateEnvironment();?>
<?php endforeach;?>
</body>
