<?php
/**
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 *
 * @license GPL 2.0
 * @package Comwrap/Pdf/Templates
 * @author Thomas Spigel <tspigel@comwrap.com>
 * @version 1.0
 *
 * @var $this Comwrap_Pdf_Block_Invoice
 */
$logoUrl = Mage::getStoreConfig('design/header/logo_src');

$i = 0;
?>

<head>
    <style type="text/css">
        body {
            font-size: 9pt;
            font-family: "helvetica";
        }
        h1 {
            text-align: center;
            padding: 0;
            margin: 0 auto;
        }
        table
        {
            border-collapse: collapse;
            width: 100%;
            border: 0.5pt solid #737373;
            padding: 0;
        }
        table tr:first-child td:first-child { border-left: 0; border-top: 0; padding:2.5pt 5pt;}
        table td
        {
            padding: 5pt;
        }
        .border-right
        {
            border-right: 0.5pt solid #737373;
        }
        .border-bottom
        {
            border-bottom: 0.5pt solid #737373;
        }
        .no-border
        {
            border: 0;
        }
        thead tr th
        {
            font-weight: bold;
            padding: 5pt;
        }

        .addresses td {
            vertical-align: top;
        }

        .products td {
            padding: 3pt;
            height: 5pt;
            vertical-align: top;
            border: solid #737373;
            border-width: 0 0.5pt 0 0.5pt;
        }

        .products tr.gray td {
            background-color: #f0f0f0;
        }

        .products thead tr {
            padding: 3pt !important;
            height: 5pt;
            background-color: #ebebeb;
        }

        .products thead tr th {
            border: 0.5pt solid #737373;
            font-weight: normal !important;
            padding: 3pt !important;
            height: 5pt;
        }

        .totals td {
            font-weight: bold;
            padding: 3pt;
            padding-right: 0pt;
        }

        .product-options {
            font-size: 8pt;
        }

        .collector-box {
            display: inline-block;
            border-top: 1px solid black;
            text-align: center;
        }

        tr.parent-product td {
            font-weight: bold;
        }
    </style>
</head>
<body>

<?php /* @var $_invoice Mage_Sales_Model_Order_Invoice */ ?>
<?php foreach($this->getInvoice() as $_invoice):?>
    <?php $this->startEmulateEnvironment($_invoice->getStoreId());?>
    <?php if($i > 0) : ?>
        <pagebreak />
    <?php endif;?>
    <?php

    $this->setOrder($_invoice->getOrder());

    $need_receipt = 0;
    if (Mage::helper('core')->isModuleEnabled('Amasty_Orderattr')) {
        $need_receipt = Mage::getModel('amorderattr/attribute')
            ->load($_invoice->getOrder()->getId(), 'order_id')
            ->getData('need_receipt');
    }

    /* 
     * ASSUMPTION 1:
     *   The price are either exclusively in the parent or children rows only.
     */

    /*
     * The invoice item collection looks like
     *   Parent Item 1
     *   Child Item 1.1
     *   Child Item 1.2
     *   Parent Item 2
     *   Child Item 2.1
     *   Child Item 2.2
     *    .
     *    .
     *    .
     * .
     * From the above we make something like 
     *   array(
     *     parent_item_1 => array(child_item_1.1, ...)
     *     parent_item_2 => array(child_item_2.1, ...)
     *     ...
     */
    $invoiceItems = array();
    $lastParentItem = null;
    $lastParentItemDeposit = 0;
    $lastParentItemFxCostTotal = 0;
    $lastParentItemTotal = 0;
    $lastParentItemDiscountTotal = 0;
    $lastChildrenList = array();

    $depositItems = array();
    $depositGrandTotal = 0;
    $fxCostGrandTotal = 0;

    foreach($_invoice->getItemsCollection() as $_item) {
        if (
            (strpos($_item->getSku(), 'deposit') !== false)
            and ($_item->getOrderItem()->getParentItem())
        ) {
            if (! $_item->getRowTotal()) {
                $p = Mage::getModel('catalog/product')->load($_item->getProductId());
                $_item->setRowTotal($p->getPrice() * $_item->getQty());
            }
            if ($_item->getOrderItem()->getParentItem()) {
                $lastParentItemDeposit += $_item->getRowTotal() - $_item->getDiscountAmount();
            }
            $depositGrandTotal += $_item->getRowTotal() - $_item->getDiscountAmount();
            $depositItems[] = $_item;
            continue;
        }

        if ($_item->getOrderItem()->getParentItem()) {
            $lastChildrenList[] = $_item;
        } else {
            if ($lastParentItem) {
                $lastParentItem->setChildrenItems($lastChildrenList);
                // the parent price is either null/0 or the whole price
                $lastParentItem->setRowTotal(max(
                    0,
                    $lastParentItem->getRowTotal() - $lastParentItemDeposit
                ));
                $lastParentItem->setFxCostTotal($lastParentItemFxCostTotal);
                $fxCostGrandTotal += $lastParentItemFxCostTotal;
                $lastParentItem->setItemTotal($lastParentItemTotal - $lastParentItemDeposit);
                $lastParentItem->setItemDiscountTotal($lastParentItemDiscountTotal);
                $invoiceItems[] = $lastParentItem;
            }
            $lastParentItem = $_item;
            $lastParentItemDeposit = 0;
            $lastParentItemFxCostTotal = 0;
            $lastParentItemTotal = 0;
            $lastParentItemDiscountTotal = 0;
            $lastChildrenList = array();
        }

        $_quoteItem = Mage::getModel('sales/quote_item')->load($_item->getOrderItem()->getQuoteItemId());
        $_item->setQuoteItem($_quoteItem);
        $useFxr = $_quoteItem->getTopupUseFxReserve();
        if ($useFxr) {
            $fxr = Mage::getModel('instasim_topupproduct/fxreserve')->load($_quoteItem->getTopupFxReserve());
            $fxd = Mage::getModel('instasim_topupproduct/deposit')->load($_quoteItem->getTopupFxDeposit());

            $_item->setUseFxr(1);
            $_item->setFxr($fxr);
            $_item->setFxd($fxd);
            $_item->setFxCost($_item->getQty() * $_quoteItem->getTopupFxCost() * $fxd->getExchangeRate());

            $lastParentItemFxCostTotal += $_item->getFxCost();
        }
        $lastParentItemTotal += $_item->getRowTotal();
        // See assumption 1
        $lastParentItemDiscountTotal += $_item->getDiscountAmount();
    }
    if ($lastParentItem) {
        $lastParentItem->setChildrenItems($lastChildrenList);
        // the parent price is either null/0 or the whole price
        $lastParentItem->setRowTotal(max(
            0,
            $lastParentItem->getRowTotal() - $lastParentItemDeposit
        ));
        $lastParentItem->setFxCostTotal($lastParentItemFxCostTotal);
        $fxCostGrandTotal += $lastParentItemFxCostTotal;
        $lastParentItem->setItemTotal($lastParentItemTotal - $lastParentItemDeposit);
        $lastParentItem->setItemDiscountTotal($lastParentItemDiscountTotal);
        $invoiceItems[] = $lastParentItem;
    }
    ?>

    <table class="no-border" style="margin-bottom: 1cm;">
        <tr>
            <td style="width: 50%; height: 3cm; overflow: hidden;">
                <?php if ($need_receipt) {
                    echo $this->getLayout()->createBlock('cms/block')->setBlockId('store_billing_contact')->toHtml(); 
                } ?>
            </td>
            <td style="width: 50%; height: 3cm; overflow: hidden; text-align: right; vertical-align: top;">
                <?php if ($need_receipt): ?>
                    <h1><?php echo $this->__('Bill')?></h1><br />
                <?php endif; ?>
                <?php echo $this->__('Order Date: '); ?>
                <?php echo Mage::helper('core')->formatDate($this->getOrder()->getCreatedAt(), 'medium', false); ?>
            </td>
        </tr>
    </table>

    <table class="no-border addresses">
        <tr>
            <td style="text-align: right; width: 13%; height: 3cm; overflow: hidden;">
                <div style="position: absolute; rotate: -90; left: 10%; text-align: center; font-size: 70%;">
                    <?php echo $this->__('Order # ')?>
                    <br />
                    <barcode code="<?php echo $_invoice->getOrder()->getIncrementId()?>" type="C128A" size="0.5" />
                    <br />
                    <?php echo $_invoice->getOrder()->getIncrementId()?>
                </div>
            </td>
            <?php if (! empty($_invoice->getShippingAddress())): ?>
                <td style="text-align: center; width: 5%; height: 3cm; overflow: hidden;">
                    S<br />
                    H<br />
                    I<br />
                    P<br />
                     <br />
                    T<br />
                    O<br />
                </td>
                <td style="padding: 5pt; text-align: left; width: 52%; height: 3cm; overflow: hidden;">
                    <p class="address-info"><?php echo $_invoice->getShippingAddress()->format('html');?></p>
                </td>
                <?php $extra_billing_width = 0; ?>
            <?php else: ?>
                <?php $extra_billing_width = 57; ?>
            <?php endif; ?>
            <td style="text-align: center; width: 5%; height: 3cm; overflow: hidden;">
                S<br />
                O<br />
                L<br />
                D<br />
                 <br />
                T<br />
                O<br />
            </td>
            <td style="padding: 5pt; text-align: left; width: <?php echo (25 + $extra_billing_width) ?>%; height: 3cm; overflow: hidden;">
                <?php if (! empty($_invoice->getBillingAddress())): ?>
                    <p class="address-info"><?php echo $_invoice->getBillingAddress()->format('html');?></p>
                <?php endif; ?>
            </td>
        </tr>
    </table>
    <table class="products" cellpadding="0" cellspacing="0" style="margin-top: 1.5cm;">
        <thead>
        <tr>
            <th rowspan="2"><?php echo $this->__('Products'); ?></th>
            <th colspan="2"><?php echo $this->__('Sub-Item'); ?></th>
            <th rowspan="2"><?php echo $this->__('Price'); ?></th>
            <th rowspan="2"><?php echo $this->__('Discount'); ?></th>
        </tr>
        <tr>
            <th><?php echo $this->__('Price'); ?></td>
            <th><?php echo $this->__('Discount'); ?></td>
        </tr>
        </thead>
        <tbody>
        <?php $grayRow = true; ?>
        <?php /* @var $_item Mage_Sales_Model_Order_Invoice_Item */?>
        <?php foreach($invoiceItems as $_item): ?>
            <?php $grayRow = ! $grayRow; ?>
            <tr class="<?php echo $grayRow ? 'gray' : ""; ?> parent-product">
                <?php
                $productOptions = $_item->getOrderItem()->getProductOptions();
                ?>
                <?php if(!empty($productOptions['attributes_info'])): ?>
                    <td>
                        <?php echo (int)$_item->getQty() ." x ". $_item->getName();?>
                        <?php foreach($productOptions['attributes_info'] as $productOption):?>
                            <br />
                            <span class="product-options">
                                <i><?php echo $productOption['label']?></i><br />
                                &nbsp;&nbsp;&nbsp;&nbsp;<?php echo $productOption['value'];?>
                            </span>
                        <?php endforeach;?>
                    </td>
                <?php else: ?>
                    <td><?php echo (int)$_item->getQty() ." x ". $_item->getName() ?></td>
                <?php endif;?>

                <td style="text-align: right;">-----</td>
                <td style="text-align: right;">-----</td>
                <td style="text-align: right;"><?php echo Mage::helper('core')->currency($_item->getItemTotal()); ?></td>
                <td style="text-align: right;"><?php echo Mage::helper('core')->currency($_item->getItemDiscountTotal()); ?></td>
            </tr>
            <?php foreach($_item->getChildrenItems() as $_childItem): ?>
                <tr class="<?php echo $grayRow ? 'gray' : ""; ?>">
                    <td style="padding-left: 1cm"><?php echo ($_childItem->getRowTotal() ? (int)$_childItem->getQty() . " x " : "") . $_childItem->getName() ?></td>
                    <td style="text-align: right;"><?php echo $_childItem->getRowTotal() ? Mage::helper('core')->currency($_childItem->getRowTotal()) : ""; ?></td>
                    <td style="text-align: right;"><?php echo $_childItem->getRowTotal() ? Mage::helper('core')->currency($_childItem->getDiscountAmount()) : ""; ?></td>
                    <td style="text-align: right;"></td>
                    <td style="text-align: right;"></td>
                </tr>
                <?php if ($_childItem->getFxCost()): ?>
                    <tr class="<?php echo $grayRow ? 'gray' : ""; ?>"><!-- The FX Cost -->
                        <td style="padding-left: 1.5cm">(*) <?php echo (int)$_item->getQty() ." x ". $this->__('Credit value of %1$.2f %2$s at the exchange rate %3$.2f %4$s/%5$s', $_childItem->getQuoteItem()->getTopupFxCost(), $_childItem->getFxr()->getCurrencySymbol(), $_childItem->getFxd()->getExchangeRate(), Mage::app()->getStore()->getBaseCurrencyCode(), $_childItem->getFxr()->getCurrencySymbol()); ?></td>
                        <td style="text-align: right;"><?php echo Mage::helper('core')->currency($_childItem->getFxCost())?></td>
                        <td style="text-align: right;"><?php echo Mage::helper('core')->currency(0)?></td>
                        <td style="text-align: right;"></td>
                        <td style="text-align: right;"></td>
                    </tr>
                <?php endif; ?>
            <?php endforeach; ?>
            <?php if ($_item->getFxCost()): ?>
                <tr class="<?php echo $grayRow ? 'gray' : ""; ?>"><!-- The FX Cost -->
                    <td style="padding-left: 1cm">(*) <?php echo (int)$_item->getQty() ." x ". $this->__('Credit value of %1$.2f %2$s at the exchange rate %3$.2f %4$s/%5$s', $_item->getQuoteItem()->getTopupFxCost(), $_item->getFxr()->getCurrencySymbol(), $_item->getFxd()->getExchangeRate(), Mage::app()->getStore()->getBaseCurrencyCode(), $_item->getFxr()->getCurrencySymbol()); ?></td>
                    <td style="text-align: right;"><?php echo Mage::helper('core')->currency($_item->getFxCost())?></td>
                    <td style="text-align: right;"><?php echo Mage::helper('core')->currency(0)?></td>
                    <td style="text-align: right;"></td>
                    <td style="text-align: right;"></td>
                </tr>
            <?php endif; ?>
            <?php if ($_item->getFxCostTotal()): ?>
                <tr class="<?php echo $grayRow ? 'gray' : ""; ?>"><!-- The Rest -->
                    <td style="padding-left: 1cm"><?php echo $_item->getOrderItem()->getNonTopupValueLabel() ?: $this->__('SIM fee'); ?></td>
                    <td style="text-align: right;"><?php echo Mage::helper('core')->currency($_item->getItemTotal() - $_item->getFxCostTotal())?></td>
                    <td style="text-align: right;"><?php echo $_item->getRowTotal() ? Mage::helper('core')->currency($_item->getDiscountAmount()) : ""; // See assumption 1?></td>
                    <td style="text-align: right;"></td>
                    <td style="text-align: right;"></td>
                </tr>
            <?php endif; ?>
        <?php endforeach; ?>
        </tbody>
    </table>
    <br />
    <br /><br />
    <table class="no-border totals" style="" cellpadding="0" cellspacing="0">
        <tbody>
        <tr>
            <td style="width: 20%">&nbsp;</td>
            <td style="text-align: right; width: 65%;"><?php echo $this->__('Subtotal');?>:</td>
            <td style="text-align: right; width: 15%;"><?php echo Mage::helper('core')->currency($_invoice->getGrandTotal() - $_invoice->getShippingInclTax() - $depositGrandTotal)?></td>
        </tr>
        <tr>
            <td style="width: 20%">&nbsp;</td>
            <td style="text-align: right; width: 65%;"><?php if ($fxCostGrandTotal) echo '(*' . $this->__('Net Without Credit Value') . ': ' . Mage::helper('core')->currency($_invoice->getGrandTotal() - $_invoice->getShippingInclTax() - $depositGrandTotal - $fxCostGrandTotal) . ')'; ?></td>
            <td style="text-align: right; width: 15%;"></td>
        </tr>
        <tr>
            <td style="width: 20%">&nbsp;</td>
            <td style="text-align: right; width: 65%;"><?php echo $this->__('Shipping & Handling')?>:</td>
            <td style="text-align: right; width: 15%;"><?php echo Mage::helper('core')->currency($_invoice->getShippingInclTax())?></td>
        </tr>
        <tr>
            <td style="width: 20%">&nbsp;</td>
            <td style="text-align: right; width: 65%;"><?php echo $this->__('Grand Total')?>:</td>
            <td style="text-align: right; width: 15%;"><?php echo Mage::helper('core')->currency($_invoice->getGrandTotal() - $depositGrandTotal)?></td>
        </tr>
        <?php if ($need_receipt): ?>
            <tr>
                <td style="width: 20%">&nbsp;</td>
                <td colspan="2" style="text-align: right; width: 80%;">
                    <br />
                    <br />
                    <br />
                    <br />
                    <div class="collector-box">
                        &nbsp;
                        &nbsp;
                        &nbsp;
                        &nbsp;
                        &nbsp;
                        &nbsp;
                        &nbsp;
                        <?php echo $this->__('Collector')?>
                        &nbsp;
                        &nbsp;
                        &nbsp;
                        &nbsp;
                        &nbsp;
                        &nbsp;
                        &nbsp;
                    </div>
                </td>
            </tr>
        <?php endif; ?>
        </tbody>
    </table>
    <?php if ($depositItems): ?>
    <pagebreak />
    <?php /* BEGIN DEPOSIT RECEIPT {{{ */ ?>
    <table class="no-border" style="margin-bottom: 1cm;">
        <tr>
            <td style="width: 50%; height: 3cm; overflow: hidden;">
                <?php
                    echo $this->getLayout()->createBlock('cms/block')->setBlockId('store_billing_contact')->toHtml(); 
                ?>
            </td>
            <td style="width: 50%; height: 3cm; overflow: hidden; text-align: right; vertical-align: top;">
                <h1><?php echo $this->__('Deposit Receipt')?></h1><br />
                <?php echo $this->__('Order Date: '); ?>
                <?php echo Mage::helper('core')->formatDate($this->getOrder()->getCreatedAt(), 'medium', false); ?>
            </td>
        </tr>
    </table>
    <table class="products" cellpadding="0" cellspacing="0" style="margin-top: 1.5cm;">
        <thead>
        <tr>
            <th><?php echo $this->__('Product Deposit Detail'); ?></th>
            <th style="text-align: right;"><?php echo $this->__('Qty'); ?></th>
            <th style="text-align: right;"><?php echo $this->__('Deposit Amount'); ?></th>
            <th style="text-align: right;"><?php echo $this->__('Discount'); ?></th>
            <th style="text-align: right;"><?php echo $this->__('Subtotal'); ?></th>
        </tr>
        </thead>
        <tbody>
        <?php /* @var $_item Mage_Sales_Model_Order_Invoice_Item */?>
        <?php $grayRow = true; ?>
        <?php foreach($depositItems as $_item): ?>
            <?php $grayRow = ! $grayRow; ?>
            <?php if ($pi = $_item->getOrderItem()->getParentItem()) {
                $itemName = $pi->getName();
            } else {
                $itemName = $_item->getName();
            }
            ?>
            <tr class="<?php echo $grayRow ? 'gray' : ""; ?>">
                <td><?php echo $itemName ?></td>
                <td style="text-align: right;"><?php echo (int)$_item->getQty() ?></td>
                <td style="text-align: right;"><?php echo $_item->getRowTotal() ? Mage::helper('core')->currency($_item->getRowTotal()) : ""; ?></td>
                <td style="text-align: right;"><?php echo $_item->getRowTotal() ? Mage::helper('core')->currency($_item->getDiscountAmount()) : ""; ?></td>
                <td style="text-align: right;"><?php echo $_item->getRowTotal() ? Mage::helper('core')->currency($_item->getRowTotal() - $_item->getDiscountAmount()) : ""; ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
    <br />
    <br /><br />
    <table class="no-border totals" style="" cellpadding="0" cellspacing="0">
        <tbody>
        <tr>
            <td style="width: 60%">&nbsp;</td>
            <td style="text-align: right; width: 25%;"><?php echo $this->__('Grand Total')?>:</td>
            <td style="text-align: right; width: 15%;"><?php echo Mage::helper('core')->currency($depositGrandTotal)?></td>
        </tr>
        <tr>
            <td style="width: 60%">&nbsp;</td>
            <td colspan="2" style="text-align: right; width: 40%;">
                <br />
                <br />
                <br />
                <br />
                <div class="collector-box">
                    &nbsp;
                    &nbsp;
                    &nbsp;
                    &nbsp;
                    &nbsp;
                    &nbsp;
                    &nbsp;
                    <?php echo $this->__('Collector')?>
                    &nbsp;
                    &nbsp;
                    &nbsp;
                    &nbsp;
                    &nbsp;
                    &nbsp;
                    &nbsp;
                </div>
            </td>
        </tr>
        </tbody>
    </table>
    * <?php $this->__('We will return the deposit amount after the goods has been returned to us in good condition in due time.') ?>
    <?php /* }}} END DEPOSIT RECEIPT */ ?>
    <?php endif; ?>
    <?php ++$i;?>
    <?php $this->stopEmulateEnvironment();?>
<?php endforeach;?>
</body>
