<?php
/**
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 *
 * @license GPL 2.0
 * @package Comwrap/Pdf/Templates
 * @author Thomas Spigel <tspigel@comwrap.com>
 * @version 1.0
 *
 * @var $this Comwrap_Pdf_Block_Shipment
 */
$imageUrl = Mage::getStoreConfig('design/header/logo_src');
# Just don't show the logo for now.
$imageUrl = '';
$i = 0;
?>

<head>
    <style type="text/css">
        body {
            font-size: 9pt;
            font-family: "helvetica";
        }
        h1 {
            text-align: center;
            padding: 0;
            margin: 0 auto;
        }
        table
        {
            border-collapse: collapse;
            width: 100%;
            border: 0.5pt solid #737373;
            padding: 0;
        }
        table tr:first-child td:first-child { border-left: 0; border-top: 0; padding:2.5pt 5pt;}
        table td
        {
            padding: 5pt;
        }
        .border-right
        {
            border-right: 0.5pt solid #737373;
        }
        .border-bottom
        {
            border-bottom: 0.5pt solid #737373;
        }
        .no-border
        {
            border: 0;
        }
        thead tr th
        {
            font-weight: bold;
            padding: 5pt;
        }

        .addresses td {
            vertical-align: top;
        }

        .products td {
            padding: 3pt;
            height: 5pt;
            vertical-align: top;
        }

        .products-head {
            padding: 3pt !important;
            height: 5pt;
            background-color: #eeebeb;
        }

        .products-head td {
            border: 0.5pt solid #737373;
            font-weight: normal !important;
            padding: 3pt !important;
            height: 5pt;
        }

        .totals td {
            font-weight: bold;
            padding: 3pt;
            padding-right: 0pt;
        }

        .product-options {
            font-size: 8pt;
        }
    </style>
</head>
<body>

<?php /* @var $_shipment Mage_Sales_Model_Order_Shipment */ ?>
<?php foreach($this->getShipment() as $_shipment):?>
    <?php $this->startEmulateEnvironment($_shipment->getStoreId());?>
    <?php if($i > 0) : ?>
        <pagebreak />
    <?php endif;?>
    <?php

    $this->setOrder($_shipment->getOrder());
    ?>

    <table class="no-border" style="margin-bottom: 1cm;">
        <tr>
            <td style="width: 50%; height: 3cm; overflow: hidden;">
                <?php if($imageUrl): ?>
                <div>
                    <div style="float: left; padding-bottom: 3mm"><img width="2.6in" src="<?php echo $image?>" /></div>
                </div>
                <?php endif;?>
            </td>
            <td style="width: 50%; height: 3cm; overflow: hidden; text-align: right; vertical-align: top;">
                <h1><?php echo $this->__('Packing Slip')?></h1><br />
                <?php echo $this->__('Order Date: ')?>
                <?php echo Mage::helper('core')->formatDate($this->getOrder()->getCreatedAt(), 'medium', false); ?>
            </td>
        </tr>
    </table>

    <table class="no-border addresses">
        <tr>
            <td style="text-align: right; width: 13%; overflow: hidden;">
                <div style="position: absolute; rotate: -90; left: 10%; text-align: center; font-size: 70%;">
                    <?php echo $this->__('Order # ')?>
                    <br />
                    <barcode code="<?php echo $_shipment->getOrder()->getIncrementId()?>" type="C128A" size="0.5" />
                    <br />
                    <?php echo $_shipment->getOrder()->getIncrementId()?>
                </div>
            </td>
            <td style="text-align: center; width: 2%;">
                S<br />
                H<br />
                I<br />
                P<br />
                 <br />
                T<br />
                O<br />
            </td>
            <td style="padding: 5pt; text-align: left; width: 45%; position: relative;">
                <p class="address-info"><?php echo $_shipment->getShippingAddress()->format('html');?></p>
            </td>
            <td style="text-align: center; width: 5%">
                S<br />
                O<br />
                L<br />
                D<br />
                 <br />
                T<br />
                O<br />
            </td>
            <td style="padding: 5pt; text-align: left; width: 35%">
                <p class="address-info"><?php echo $_shipment->getBillingAddress()->format('html');?></p>
            </td>
        </tr>
    </table>
    <table class="no-border products" cellpadding="0" cellspacing="0" style="margin-top: 1.5cm;">
        <thead>
        <tr class="products-head">
            <td style="border-right: 0;"><?php echo $this->__('Products'); ?></td>
            <td style="text-align: right; border-left: 0;"><?php echo $this->__('Qty'); ?></td>
        </tr>
        </thead>
        <tbody>
        <?php /* @var $_item Mage_Sales_Model_Order_Shipment_Item */?>
        <?php foreach($_shipment->getItemsCollection() as $_item): ?>
        <?php if ($_item->getOrderItem()->getParentItem()) continue; ?>
            <tr>
                <?php $productOptions = $_item->getOrderItem()->getProductOptions();
                if(!empty($productOptions['attributes_info'])):?>
                    <td>
                        <?php echo $_item->getName();?>
                        <?php foreach($productOptions['attributes_info'] as $productOption):?>
                            <br />
                            <span class="product-options">
                                <i><?php echo $productOption['label']?></i><br />
                                &nbsp;&nbsp;&nbsp;&nbsp;<?php echo $productOption['value'];?>
                            </span>
                        <?php endforeach;?>
                    </td>
                <?php else: ?>
                    <td><?php echo $_item->getName() ?></td>
                <?php endif;?>

                <td style="text-align: right;"><?php echo (int)$_item->getQty() ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
    <?php ++$i;?>
    <?php $this->stopEmulateEnvironment();?>
<?php endforeach;?>
</body>
